### ISSUE TITLE
Tinker script user overview returns wrong pincode for phone verification

### ISSUE THREAD

**Issue by fe-ax** [bunq/tinker_php#25]
See https://fe.ax/1535464136-9815f3f04ba8e4549cf1d9f87bc481b2.20180828154856.png

and https://together.bunq.com/d/4077-can-t-get-sandbox-app-to-work

**Comment by OGKevin** [comment]
Your title already says to different terms 😊

You are entering a  login code as confirmation code..... that won't work of course. 

The login code is the code you use to... well login 😋. The confirmation code you receive it via SMS. When you register the device you are using to access the sandbox.

**Comment by fe-ax** [comment]
How could I've known that I should've user 992266 without the help of Gregory?

**Comment by OGKevin** [comment]
Did you provide a working phone number when you registered the device ?

**Comment by fe-ax** [comment]
Yes, at first I did, but the SMS never came through, neither did the call. Then I found you can't use your real phone number and have to create a account using a tinker script (or your own implementation, but that would be weird since you're trying to start developing). The tinker script returns a "login key" for a phone number that is mentioned in the overview.

edit: https://together.bunq.com/d/3694-accepting-draft-payments-the-sandbox-app a topic I could find with the keyword 992266 in which bastiaan says the SMS function is disabled in the sandbox app. I couldn't find this topic before, else I would've found the confirmation code ofcourse.

**Comment by OGKevin** [comment]
I just took a look. And it seems to be a miscommunication internally. There has been some changes. 

The old scenario you got an SMS with the confirmation code. It seem now that everything has been hardcoded 🤦‍♂️. This means, the confirmation code will always be `123456` and you can use a random phone number to register the device, because no SMS will be sent. I also did not know about this change 😔. 

So, you are indeed correct and I was wrong, well I was talking about our old sandbox structure. Ill reopen this issue, feel free to make an MR to add a little text to tinker.
